"""Add entities and relationships tables with updated schema

Revision ID: 0c0cc65846c7
Revises: 202512291234
Create Date: 2025-12-29 21:08:11.887525

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c0cc65846c7"
down_revision = "202512291234"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_name", sa.String(length=500), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_entity_id", "entities", ["entity_id"], unique=False)
    op.create_index(
        "idx_entity_name_type", "entities", ["entity_name", "entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_entities_entity_name"), "entities", ["entity_name"], unique=False
    )
    op.create_index(
        op.f("ix_entities_entity_type"), "entities", ["entity_type"], unique=False
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_entity_id", sa.Integer(), nullable=False),
        sa.Column("target_entity_id", sa.Integer(), nullable=True),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("relationship_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_relationship_record", "relationships", ["record_id"], unique=False
    )
    op.create_index(
        "idx_relationship_source", "relationships", ["source_entity_id"], unique=False
    )
    op.create_index(
        "idx_relationship_target", "relationships", ["target_entity_id"], unique=False
    )
    op.create_index(
        "idx_relationship_type", "relationships", ["relationship_type"], unique=False
    )
    op.create_index(
        op.f("ix_relationships_relationship_type"),
        "relationships",
        ["relationship_type"],
        unique=False,
    )
    op.add_column(
        "data_source", sa.Column("source_type", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "data_source", sa.Column("api_endpoint", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "data_source", sa.Column("status", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "data_source", sa.Column("last_scraped", sa.DateTime(), nullable=True)
    )
    op.add_column("data_source", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("data_source", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("data_source", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "data_source", "url", existing_type=sa.VARCHAR(length=1024), nullable=True
    )
    op.create_index(
        "idx_data_source_jurisdiction", "data_source", ["jurisdiction_id"], unique=False
    )
    op.create_index("idx_data_source_status", "data_source", ["status"], unique=False)
    op.add_column(
        "jurisdiction", sa.Column("country", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "jurisdiction", sa.Column("type", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "jurisdiction", sa.Column("api_available", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "jurisdiction", sa.Column("scraper_needed", sa.Boolean(), nullable=True)
    )
    op.add_column("jurisdiction", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "jurisdiction", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "jurisdiction", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.alter_column(
        "jurisdiction", "state", existing_type=sa.VARCHAR(length=2), nullable=True
    )
    op.alter_column(
        "jurisdiction", "county", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_index(
        "idx_jurisdiction_state_county",
        "jurisdiction",
        ["state", "county"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jurisdiction_county"), "jurisdiction", ["county"], unique=False
    )
    op.create_index(op.f("ix_jurisdiction_name"), "jurisdiction", ["name"], unique=True)
    op.create_index(
        op.f("ix_jurisdiction_state"), "jurisdiction", ["state"], unique=False
    )
    op.add_column("record", sa.Column("jurisdiction_id", sa.Integer(), nullable=False))
    op.add_column("record", sa.Column("title", sa.String(length=500), nullable=False))
    op.add_column("record", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("record", sa.Column("amount", sa.Float(), nullable=True))
    op.add_column("record", sa.Column("date", sa.Date(), nullable=True))
    op.add_column("record", sa.Column("url", sa.String(length=1000), nullable=True))
    op.add_column(
        "record", sa.Column("record_type", sa.String(length=100), nullable=True)
    )
    op.add_column("record", sa.Column("status", sa.String(length=50), nullable=True))
    op.add_column("record", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("record", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "record",
        "data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.create_index(
        "idx_record_data_source", "record", ["data_source_id"], unique=False
    )
    op.create_index("idx_record_date", "record", ["date"], unique=False)
    op.create_index(
        "idx_record_jurisdiction", "record", ["jurisdiction_id"], unique=False
    )
    op.create_index("idx_record_type", "record", ["record_type"], unique=False)
    op.create_foreign_key(None, "record", "jurisdiction", ["jurisdiction_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "record", type_="foreignkey")
    op.drop_index("idx_record_type", table_name="record")
    op.drop_index("idx_record_jurisdiction", table_name="record")
    op.drop_index("idx_record_date", table_name="record")
    op.drop_index("idx_record_data_source", table_name="record")
    op.alter_column(
        "record",
        "data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_column("record", "updated_at")
    op.drop_column("record", "created_at")
    op.drop_column("record", "status")
    op.drop_column("record", "record_type")
    op.drop_column("record", "url")
    op.drop_column("record", "date")
    op.drop_column("record", "amount")
    op.drop_column("record", "description")
    op.drop_column("record", "title")
    op.drop_column("record", "jurisdiction_id")
    op.drop_index(op.f("ix_jurisdiction_state"), table_name="jurisdiction")
    op.drop_index(op.f("ix_jurisdiction_name"), table_name="jurisdiction")
    op.drop_index(op.f("ix_jurisdiction_county"), table_name="jurisdiction")
    op.drop_index("idx_jurisdiction_state_county", table_name="jurisdiction")
    op.alter_column(
        "jurisdiction", "county", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "jurisdiction", "state", existing_type=sa.VARCHAR(length=2), nullable=False
    )
    op.drop_column("jurisdiction", "updated_at")
    op.drop_column("jurisdiction", "created_at")
    op.drop_column("jurisdiction", "description")
    op.drop_column("jurisdiction", "scraper_needed")
    op.drop_column("jurisdiction", "api_available")
    op.drop_column("jurisdiction", "type")
    op.drop_column("jurisdiction", "country")
    op.drop_index("idx_data_source_status", table_name="data_source")
    op.drop_index("idx_data_source_jurisdiction", table_name="data_source")
    op.alter_column(
        "data_source", "url", existing_type=sa.VARCHAR(length=1024), nullable=False
    )
    op.drop_column("data_source", "updated_at")
    op.drop_column("data_source", "created_at")
    op.drop_column("data_source", "description")
    op.drop_column("data_source", "last_scraped")
    op.drop_column("data_source", "status")
    op.drop_column("data_source", "api_endpoint")
    op.drop_column("data_source", "source_type")
    op.drop_index(
        op.f("ix_relationships_relationship_type"), table_name="relationships"
    )
    op.drop_index("idx_relationship_type", table_name="relationships")
    op.drop_index("idx_relationship_target", table_name="relationships")
    op.drop_index("idx_relationship_source", table_name="relationships")
    op.drop_index("idx_relationship_record", table_name="relationships")
    op.drop_table("relationships")
    op.drop_index(op.f("ix_entities_entity_type"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_name"), table_name="entities")
    op.drop_index("idx_entity_name_type", table_name="entities")
    op.drop_index("idx_entity_id", table_name="entities")
    op.drop_table("entities")
    # ### end Alembic commands ###
