"""create users table

Revision ID: 1a2b3c4d5e6f
Revises: 0c0cc65846c7
Create Date: 2026-01-12 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = '0c0cc65846c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('api_calls_today', sa.Integer(), nullable=False),
    sa.Column('api_calls_reset_at', sa.DateTime(), nullable=True),
    sa.Column('exports_this_month', sa.Integer(), nullable=False),
    sa.Column('exports_reset_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_disabled', 'users', ['disabled'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=True)
    op.create_index('idx_user_reset_token', 'users', ['password_reset_token'], unique=False)
    op.create_index('idx_user_stripe_customer', 'users', ['stripe_customer_id'], unique=True)
    op.create_index('idx_user_stripe_subscription', 'users', ['stripe_subscription_id'], unique=True)
    op.create_index('idx_user_subscription', 'users', ['subscription_tier'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_subscription', table_name='users')
    op.drop_index('idx_user_stripe_subscription', table_name='users')
    op.drop_index('idx_user_stripe_customer', table_name='users')
    op.drop_index('idx_user_reset_token', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_disabled', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
