"""Initial migration

Revision ID: 202512291234
Revises: 
Create Date: 2025-12-29 20:34:00.000000

"""
from alembic import op
import sqlalchemy as sa

from datagod.models.data_source import DataSource
from datagod.models.jurisdiction import Jurisdiction
from datagod.models.record import Record

# revision identifiers, used by Alembic.
revision = '202512291234'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdiction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('data_source')
    op.drop_table('jurisdiction')
    # ### end Alembic commands ###
