"""
Data Category Scrapers

This module provides specialized scrapers for different data categories:

Core Categories:
- Court Records (civil, criminal, family, probate)
- Business Filings (corporations, LLCs, partnerships, UCC)
- Professional Licenses (real estate, loan officers, attorneys)
- Federal Sources (USPTO, SEC EDGAR, FDIC, Census, BLS, FHFA)
- News API (NewsAPI.org, local news aggregation)

Federal API Integrations:
- FEC API (Federal Election Commission - campaign finance)
- FDA API (Food and Drug Administration - recalls, adverse events)
- EPA API (Environmental Protection Agency - facilities, violations)
- FMCSA API (Federal Motor Carrier Safety - carrier data, inspections)

New Data Categories:
- Vital Records (death, marriage, divorce, burial)
- Criminal Records (sex offenders, inmates, warrants, most wanted)
- Voter Records (voter registration, campaign contributions, elections)
- Regulatory Records (OSHA, SEC, CPSC, state regulatory agencies)
- Financial Records (bankruptcy, nonprofits, unclaimed property, liens)
- Asset Records (aircraft, vessels, boats)
- Education Records (schools, colleges, teacher licenses)
- Employment Records (federal awards, government salaries, pensions)
- Health Safety Records (healthcare providers, hospitals, nursing homes)
- Transportation Records (VIN decode, recalls, complaints, safety ratings)

Additional Specialized Categories:
- Lottery Winners (state lottery commission winner records)
- Registered Agents (Secretary of State registered agent databases)
- Childcare Licenses (state childcare facility licensing)
- Veterinary Licenses (state veterinary board license databases)
- Immigration Court (DOJ EOIR - courts, statistics, precedent decisions)
- Foster Care (state child welfare agencies, statistics)
- Pest Control Licenses (state agriculture departments)
- Campaign Donors (state election boards, campaign finance)
"""

from datagod.scrapers.categories.court_records import (
    CourtRecordsScraper,
    CaseSearch,
    PartySearch,
    CourtCase,
    CaseParty,
    CaseType,
    CaseStatus,
    PartyType,
    StateCourtScraper,
    search_court_records
)

from datagod.scrapers.categories.business_filings import (
    BusinessFilingsScraper,
    BusinessEntity,
    UCCFiling,
    EntityType,
    EntityStatus,
    FilingType,
    RegisteredAgent,
    Officer,
    BusinessFiling,
    StateSOSScraper,
    BusinessFilingsAPI,
    search_businesses,
    search_ucc,
    search_state_businesses,
    get_company_details,
    get_available_states as get_business_filings_states,
)

from datagod.scrapers.categories.professional_licenses import (
    ProfessionalLicensesScraper,
    LicenseSearch,
    ProfessionalLicense,
    LicenseType,
    LicenseStatus,
    DisciplinaryAction,
    Employer,
    StateLicenseBoardScraper,
    NMLSScraper,
    ProfessionalLicensesAPI,
    search_professional_licenses,
    verify_professional_license,
    search_healthcare_providers,
    verify_npi_number,
    search_mortgage_professionals,
    verify_nmls_license,
)

from datagod.scrapers.categories.federal_sources import (
    # USPTO
    USPTOScraper,
    Trademark,
    Patent,
    TrademarkSearch,
    PatentSearch,
    TrademarkStatus,
    PatentType,
    PatentStatus,
    # SEC EDGAR
    SECEdgarScraper,
    SECFiling,
    SECCompany,
    SECSearch,
    SECFilingType,
    # FDIC
    FDICScraper,
    Bank,
    BankBranch,
    BankSearch,
    BankStatus,
    # Census
    CensusScraper,
    CensusData,
    CensusSearch,
    # FHFA
    FHFAScraper,
    HousePriceIndex,
    # BLS
    BLSScraper,
    LaborStatistic,
    UnemploymentData,
    # Convenience functions
    search_trademarks,
    search_sec_filings,
    search_banks
)

from datagod.scrapers.categories.news_api import (
    # NewsAPI
    NewsAPIScraper,
    NewsArticle,
    NewsSource,
    NewsSearch,
    NewsCategory,
    NewsSentiment,
    NewsSourceType,
    # Google News
    GoogleNewsScraper,
    # Local News
    LocalNewsAggregator,
    # Press Releases
    PressReleaseAggregator,
    PressRelease,
    # Entity News
    EntityNewsFinder,
    EntityNewsSearch,
    # Convenience functions
    search_news,
    search_entity_news,
    get_local_headlines
)

# Federal API integrations
from datagod.scrapers.categories.fec_api import (
    FECApiClient,
    FECCandidate,
    FECCommittee,
    FECContribution,
    CandidateOffice,
    CandidateStatus,
    PartyAffiliation,
    CommitteeType,
    search_fec_candidates,
    search_fec_contributions
)

from datagod.scrapers.categories.fda_api import (
    FDAApiClient,
    FDAEndpoint,
    DrugAdverseEvent,
    DrugRecall,
    DeviceRecall,
    FoodRecall,
    DrugLabel,
    RecallClassification,
    RecallStatus,
    search_drug_adverse_events_sync,
    search_drug_recalls_sync,
    search_food_recalls_sync
)

from datagod.scrapers.categories.epa_api import (
    EPAApiClient,
    EPADatabase,
    EPAFacility,
    EPAViolation,
    EPAEnforcement,
    TRIRelease,
    SuperfundSite,
    AirQualityData,
    WaterSystem,
    ViolationType,
    ComplianceStatus,
    search_facilities_sync,
    search_violations_sync,
    search_superfund_sites_sync
)

from datagod.scrapers.categories.fmcsa_api import (
    FMCSAApiClient,
    Carrier,
    CarrierBasics,
    Inspection,
    Crash,
    OperatingAuthority,
    CarrierOperationType,
    SafetyRating,
    OperatingStatus,
    get_carrier_sync,
    search_carriers_sync,
    get_carrier_inspections_sync
)

# New Data Category Scrapers
from datagod.scrapers.categories.vital_records import (
    VitalRecordsScraper,
    DeathRecord,
    MarriageRecord,
    DivorceRecord,
    BurialRecord,
    RecordType,
    RecordSource,
    get_vital_records_office,
    search_death_records_sync
)

from datagod.scrapers.categories.criminal_records import (
    CriminalRecordsScraper,
    SexOffender,
    Inmate,
    Warrant,
    MostWanted,
    CriminalCase,
    OffenderType,
    InmateStatus,
    WarrantType,
    CrimeCategory,
    search_sex_offenders_sync,
    search_inmates_sync
)

from datagod.scrapers.categories.voter_records import (
    VoterRecordsScraper,
    VoterRegistration,
    CampaignContribution,
    ElectionResult,
    StateVoterAccess,
    VoterStatus,
    VoterFileAccess,
    PartyRegistration,
    ElectionType,
    get_voter_lookup_url,
    get_state_election_resources,
    check_registration_sync
)

from datagod.scrapers.categories.regulatory_records import (
    RegulatoryRecordsScraper,
    OSHAInspection,
    OSHAViolation,
    MSHAInspection,
    SECFiling as RegulatorySECFiling,
    SECEnforcement,
    ProductRecall,
    ViolationType as RegulatoryViolationType,
    InspectionType,
    SECFilingType as RegulatorySECFilingType,
    STATE_REGULATORY_URLS,
    search_osha_inspections_sync,
    search_sec_filings_sync,
    search_product_recalls_sync
)

from datagod.scrapers.categories.financial_records import (
    FinancialRecordsScraper,
    BankruptcyCase,
    TaxLien,
    Judgment,
    NonprofitOrg,
    UnclaimedProperty,
    BankruptcyChapter,
    BankruptcyStatus,
    LienType,
    NonprofitType,
    get_unclaimed_property_url,
    search_nonprofits_sync,
    get_nonprofit_990s_sync
)

from datagod.scrapers.categories.asset_records import (
    AssetRecordsScraper,
    Aircraft,
    Pilot,
    Vessel,
    StateBoatRegistration,
    AircraftCategory,
    AircraftType,
    RegistrationStatus,
    VesselType,
    VesselService,
    get_faa_resources,
    get_state_boat_url,
    search_aircraft_sync
)

from datagod.scrapers.categories.education_records import (
    EducationRecordsScraper,
    School,
    SchoolDistrict,
    TeacherLicense,
    College,
    SchoolLevel,
    SchoolType,
    LicenseStatus as EducationLicenseStatus,
    STATE_TEACHER_LICENSE_URLS,
    search_colleges_sync,
    search_schools_sync,
    search_districts_sync
)

from datagod.scrapers.categories.employment_records import (
    EmploymentRecordsScraper,
    FederalAward,
    GovernmentSalary,
    PensionRecord,
    FederalAgency,
    AwardType,
    EmployeeType,
    STATE_SALARY_DATABASES,
    STATE_PENSION_DATABASES,
    search_federal_awards_sync,
    search_federal_agencies_sync
)

from datagod.scrapers.categories.health_safety_records import (
    HealthSafetyRecordsScraper,
    HealthcareProvider,
    NursingHome,
    Hospital,
    ExcludedProvider,
    HomeHealthAgency,
    ProviderType,
    LicenseStatus as HealthLicenseStatus,
    StarRating,
    STATE_HEALTH_LICENSE_URLS,
    search_providers_sync,
    search_nursing_homes_sync,
    search_hospitals_sync
)

from datagod.scrapers.categories.transportation_records import (
    TransportationRecordsScraper,
    VehicleRecall,
    VehicleComplaint,
    VehicleSafetyRating,
    VINDecodeResult,
    CDLHolder,
    VehicleType,
    RecallStatus as VehicleRecallStatus,
    CDLClass,
    CDLEndorsement,
    STATE_DMV_URLS,
    CDL_VERIFICATION_RESOURCES,
    decode_vin_sync,
    search_recalls_sync,
    search_complaints_sync,
    get_safety_ratings_sync
)

# Additional Specialized Categories
from datagod.scrapers.categories.lottery_winners import (
    LotteryWinner,
    LotteryGame,
    PrizeType,
    PaymentOption,
    ClaimStatus,
    SearchCriteria as LotterySearchCriteria,
    SearchResult as LotterySearchResult,
    BaseLotteryAPI,
    get_lottery_api,
    search_lottery_winners,
    get_recent_lottery_winners,
    get_jackpot_winners,
    search_all_states_lottery_winners,
)

from datagod.scrapers.categories.registered_agents import (
    RegisteredAgent as RegisteredAgentRecord,
    RepresentedEntity,
    AgentStatus,
    AgentType,
    EntityType as RegisteredAgentEntityType,
    SearchCriteria as RegisteredAgentSearchCriteria,
    SearchResult as RegisteredAgentSearchResult,
    BaseRegisteredAgentAPI,
    get_registered_agent_api,
    search_registered_agents,
    search_agents_by_entity,
    search_all_states_agents,
)

from datagod.scrapers.categories.childcare_licenses import (
    ChildcareFacility,
    Inspection as ChildcareInspection,
    Violation as ChildcareViolation,
    Capacity,
    FacilityType as ChildcareFacilityType,
    LicenseStatus as ChildcareLicenseStatus,
    LicenseType as ChildcareLicenseType,
    InspectionType as ChildcareInspectionType,
    ViolationType as ChildcareViolationType,
    SearchCriteria as ChildcareSearchCriteria,
    SearchResult as ChildcareSearchResult,
    BaseChildcareAPI,
    get_childcare_api,
    search_childcare_facilities,
    search_childcare_by_zip,
    search_all_states_childcare,
)

from datagod.scrapers.categories.veterinary_licenses import (
    VeterinaryLicense,
    DisciplinaryRecord as VetDisciplinaryRecord,
    LicenseType as VetLicenseType,
    LicenseStatus as VetLicenseStatus,
    Specialty as VetSpecialty,
    DisciplinaryAction as VetDisciplinaryAction,
    SearchCriteria as VetSearchCriteria,
    SearchResult as VetSearchResult,
    BaseVeterinaryBoardAPI,
    get_vet_board_api,
    search_veterinary_licenses,
    verify_veterinary_license,
    search_all_states_vet_licenses,
)

from datagod.scrapers.categories.immigration_court import (
    ImmigrationCourt,
    ImmigrationJudge,
    JudgeStatistics,
    CourtStatistics,
    PrecedentDecision,
    NationalStatistics,
    CaseType as ImmigrationCaseType,
    CaseOutcome,
    ReliefType,
    CourtStatus,
    IMMIGRATION_COURTS,
    BaseImmigrationCourtAPI,
    get_all_immigration_courts,
    get_immigration_courts_by_state,
    get_detention_courts,
    get_national_statistics,
    get_court_statistics,
    search_precedent_decisions,
    get_judge_statistics,
    get_backlog_by_court,
    get_asylum_grant_rates
)

from datagod.scrapers.categories.foster_care import (
    ChildWelfareAgency,
    FosterCareStatistics,
    StateRequirements as FosterCareRequirements,
    AgencyType as FosterCareAgencyType,
    LicenseStatus as FosterCareLicenseStatus,
    ServiceArea,
    STATE_CHILD_WELFARE_AGENCIES,
    BaseFosterCareAPI,
    get_foster_care_api,
    get_state_child_welfare_contact,
    get_all_state_contacts,
    search_foster_care_agencies,
    get_foster_care_statistics,
    get_licensing_requirements as get_foster_care_requirements,
    search_all_states_statistics as search_all_states_foster_stats,
)

from datagod.scrapers.categories.pest_control_licenses import (
    PestControlLicense,
    DisciplinaryAction as PestControlDisciplinaryAction,
    PestControlCompany,
    LicenseType as PestControlLicenseType,
    LicenseStatus as PestControlLicenseStatus,
    CategoryType as PestControlCategory,
    STATE_PEST_CONTROL_AGENCIES,
    BasePestControlAPI,
    STATE_PEST_CONTROL_APIS,
    get_state_pest_control_agency,
    search_pest_control_licenses,
    verify_pest_control_license,
    search_pest_control_companies,
    search_all_states_pest_control,
)

from datagod.scrapers.categories.campaign_donors import (
    CampaignContribution as StateCampaignContribution,
    Candidate as StateCandidate,
    Committee as StateCommittee,
    DonorSummary,
    ContributionType,
    DonorType,
    OfficeLevel,
    ElectionCycle,
    STATE_CAMPAIGN_FINANCE,
    BaseStateCampaignFinanceAPI,
    STATE_CAMPAIGN_APIS,
    get_state_campaign_database,
    search_state_contributions,
    search_state_candidates,
    get_donor_history,
    search_all_states_contributions,
)

# Building Permits
from datagod.scrapers.categories.building_permits import (
    PermitType as BuildingPermitType,
    PermitStatus as BuildingPermitStatus,
    PropertyUse,
    Contractor,
    Inspection as BuildingInspection,
    BuildingPermit,
    BuildingPermitsAPI,
    search_permits_by_address,
    search_permits_by_owner,
    search_permits_by_contractor,
    get_permit,
    get_recent_permits,
    get_high_value_permits,
    get_available_jurisdictions as get_building_permit_jurisdictions,
)

# Census API
from datagod.scrapers.categories.census_api import (
    CensusDataset,
    GeographyLevel,
    CensusRecord,
    BusinessPatternRecord,
    PopulationEstimate,
    CensusApiScraper,
    get_census_scraper,
    get_county_demographics,
    get_county_population,
    get_available_datasets,
    get_common_variables,
    get_state_fips,
    get_all_state_fips,
)

# Code Violations
from datagod.scrapers.categories.code_violations import (
    ViolationType as CodeViolationType,
    ViolationStatus,
    PriorityLevel,
    ComplaintSource,
    ViolationProperty,
    PropertyOwner as ViolationPropertyOwner,
    ViolationInspection,
    ViolationFine,
    ViolationHearing,
    CodeViolationRecord,
    CodeViolationsAPI,
    search_violations_by_address,
    search_violations_by_owner,
    get_violation_by_case,
    get_open_violations,
    get_recent_violations as get_recent_code_violations,
    get_city_code_enforcement_info,
    get_available_cities as get_code_violations_cities,
    get_coverage_stats as get_code_violations_coverage_stats,
)

# DBA Filings
from datagod.scrapers.categories.dba_filings import (
    DBAFilingType,
    DBAStatus,
    BusinessStructure,
    DBARegistrant,
    DBAFiling,
    DBAFilingsAPI,
    search_dba_by_business_name,
    search_dba_by_registrant,
    get_dba_by_filing_number,
    get_filing_requirements as get_dba_filing_requirements,
    get_county_office_info as get_dba_county_office_info,
    get_state_dba_info,
    get_all_state_info as get_all_dba_state_info,
    get_coverage_stats as get_dba_coverage_stats,
)

# Environmental Records
from datagod.scrapers.categories.environmental_records import (
    EnvironmentalRecordType,
    ComplianceStatus as EnvironmentalComplianceStatus,
    EnvironmentalRecord,
    EnvironmentalRecordsScraper,
    get_environmental_scraper,
    search_facilities as search_environmental_facilities,
    get_available_sources as get_environmental_sources,
)

# Evictions
from datagod.scrapers.categories.evictions import (
    EvictionType,
    CaseStatus as EvictionCaseStatus,
    PartyRole as EvictionPartyRole,
    EvictionParty,
    EvictionEvent,
    EvictionJudgment,
    EvictionRecord,
    EvictionsAPI,
    search_evictions_by_defendant,
    search_evictions_by_plaintiff,
    search_evictions_by_address,
    get_eviction_case,
    get_recent_evictions,
    get_state_eviction_info,
    get_available_counties as get_eviction_counties,
)

# Foreclosures
from datagod.scrapers.categories.foreclosures import (
    ForeclosureStage,
    ForeclosureType,
    PropertyType as ForeclosurePropertyType,
    MortgageInfo,
    AuctionInfo,
    ForeclosureRecord,
    ForeclosuresAPI,
    search_foreclosures_by_address,
    search_foreclosures_by_county,
    search_foreclosure_auctions,
    search_reo_properties,
    get_state_foreclosure_info,
    get_available_states as get_foreclosure_states,
)

# Government Contracts
from datagod.scrapers.categories.government_contracts import (
    ContractType,
    AwardStatus,
    CompetitionType,
    ContractRecord,
    GovernmentContractsScraper,
    get_contracts_scraper,
    search_contracts,
    get_available_sources as get_contracts_sources,
)

# Hunting Fishing
from datagod.scrapers.categories.hunting_fishing import (
    LicenseType as HuntingFishingLicenseType,
    LicenseStatus as HuntingFishingLicenseStatus,
    ResidencyStatus,
    HarveyReportStatus,
    LicenseHolder,
    HarvestRecord,
    LicenseRecord as HuntingFishingLicenseRecord,
    HuntingFishingAPI,
    search_licenses_by_name as search_hunting_fishing_licenses,
    get_license_by_number as get_hunting_fishing_license,
    get_harvest_data,
    get_license_types,
    get_license_requirements,
    verify_license as verify_hunting_fishing_license,
    get_state_agency_info as get_state_dnr_info,
    get_all_state_agencies as get_all_state_dnr_agencies,
    get_federal_duck_stamp,
    get_coverage_stats as get_hunting_fishing_coverage_stats,
)

# Inmate Records
from datagod.scrapers.categories.inmate_records import (
    CustodyStatus,
    FacilityType as InmateFacilityType,
    SecurityLevel,
    InmateRecord,
    FacilityInfo,
    InmateRecordsScraper,
    get_inmate_scraper,
    search_inmates as search_inmate_records,
    search_federal_inmates,
    search_sex_offenders as search_inmate_sex_offenders,
    get_available_sources as get_inmate_sources,
)

# Mechanic Liens
from datagod.scrapers.categories.mechanic_liens import (
    LienType as MechanicLienType,
    LienStatus as MechanicLienStatus,
    ClaimantType,
    PropertyType as MechanicLienPropertyType,
    LienClaimant,
    PropertyOwner as LienPropertyOwner,
    LienProperty,
    WorkDescription,
    MechanicLienRecord,
    MechanicLiensAPI,
    search_liens_by_property,
    search_liens_by_owner as search_liens_by_lien_owner,
    search_liens_by_claimant,
    get_lien_by_document,
    get_recent_liens,
    get_lien_law_info,
    get_filing_deadline as get_lien_filing_deadline,
    get_county_recorder_info as get_lien_county_recorder_info,
    get_all_state_lien_laws,
    get_coverage_stats as get_mechanic_liens_coverage_stats,
)

# Permits Inspections
from datagod.scrapers.categories.permits_inspections import (
    PermitType as PermitsPermitType,
    InspectionType as PermitsInspectionType,
    PermitStatus as PermitsPermitStatus,
    InspectionResult as PermitsInspectionResult,
    PermitRecord,
    InspectionRecord,
    PermitsInspectionsScraper,
    get_permits_scraper,
    search_building_permits,
    get_available_sources as get_permits_sources,
)

# Probate Records
from datagod.scrapers.categories.probate_records import (
    ProbateCaseType,
    CaseStatus as ProbateCaseStatus,
    PartyRole as ProbatePartyRole,
    DocumentType as ProbateDocumentType,
    ProbateParty,
    ProbateDocument,
    ProbateAsset,
    ProbateEvent,
    ProbateRecord,
    ProbateRecordsAPI,
    search_probate_by_decedent,
    get_probate_case,
    search_probate_by_heir,
    get_recent_probate_filings,
    get_state_probate_info,
    get_county_probate_info,
    get_small_estate_limit,
    get_all_state_probate_info,
    get_coverage_stats as get_probate_coverage_stats,
)

# Property Records
from datagod.scrapers.categories.property_records import (
    PropertyRecordType,
    PropertyRecord,
    PropertyRecordsScraper,
    get_property_scraper,
    search_property,
    get_available_sources as get_property_sources,
)

# Restaurant Inspections
from datagod.scrapers.categories.restaurant_inspections import (
    InspectionType as RestaurantInspectionType,
    InspectionResult as RestaurantInspectionResult,
    FacilityType as RestaurantFacilityType,
    ViolationSeverity,
    ViolationCategory,
    Violation as RestaurantViolation,
    FoodEstablishment,
    InspectionRecord as RestaurantInspectionRecord,
    RestaurantInspectionsAPI,
    search_inspections_by_restaurant as search_restaurant_inspections,
    search_inspections_by_address as search_restaurant_by_address,
    get_recent_inspections as get_recent_restaurant_inspections,
    get_failed_inspections,
    get_critical_violations,
    get_establishment_history,
    get_available_jurisdictions as get_restaurant_jurisdictions,
    get_state_health_info,
    get_coverage_stats as get_restaurant_coverage_stats,
)

# SEC API
from datagod.scrapers.categories.sec_api import (
    FilingType as SECApiFilingType,
    FilingStatus as SECApiFilingStatus,
    SECFiling as SECApiFilingRecord,
    InsiderTransaction,
    SECApiScraper,
    get_sec_scraper as get_sec_api_scraper,
    search_sec_filings as search_sec_api_filings,
    get_available_endpoints as get_sec_endpoints,
)

# Tax Records
from datagod.scrapers.categories.tax_records import (
    TaxRecordType,
    TaxStatus,
    TaxRecord,
    TaxRecordsScraper,
    get_tax_scraper,
    search_property_taxes,
    get_available_sources as get_tax_sources,
)

# UCC Filings
from datagod.scrapers.categories.ucc_filings import (
    UCCFilingType,
    UCCStatus,
    DebtorType,
    CollateralType,
    UCCParty,
    UCCAmendment,
    UCCFiling as UCCFilingRecord,
    UCCFilingsAPI,
    search_ucc_by_debtor,
    search_ucc_by_secured_party,
    search_ucc_by_state,
    get_ucc_filing,
    get_available_states as get_ucc_available_states,
)

# USPTO API
from datagod.scrapers.categories.uspto_api import (
    PatentType as USPTOPatentType,
    PatentStatus as USPTOPatentStatus,
    TrademarkStatus as USPTOTrademarkStatus,
    PatentRecord,
    TrademarkRecord as USPTOTrademarkRecord,
    USPTOApiScraper,
    get_uspto_scraper,
    search_patents,
    search_trademarks as search_uspto_trademarks,
    get_available_endpoints as get_uspto_endpoints,
)

__all__ = [
    # Court Records
    'CourtRecordsScraper',
    'CaseSearch',
    'PartySearch',
    'CourtCase',
    'CaseParty',
    'CaseType',
    'CaseStatus',
    'PartyType',
    'StateCourtScraper',
    'search_court_records',
    # Business Filings
    'BusinessFilingsScraper',
    'BusinessEntity',
    'UCCFiling',
    'EntityType',
    'EntityStatus',
    'FilingType',
    'RegisteredAgent',
    'Officer',
    'BusinessFiling',
    'StateSOSScraper',
    'BusinessFilingsAPI',
    'search_businesses',
    'search_ucc',
    'search_state_businesses',
    'get_company_details',
    'get_business_filings_states',
    # Professional Licenses
    'ProfessionalLicensesScraper',
    'LicenseSearch',
    'ProfessionalLicense',
    'LicenseType',
    'LicenseStatus',
    'DisciplinaryAction',
    'Employer',
    'StateLicenseBoardScraper',
    'NMLSScraper',
    'ProfessionalLicensesAPI',
    'search_professional_licenses',
    'verify_professional_license',
    'search_healthcare_providers',
    'verify_npi_number',
    'search_mortgage_professionals',
    'verify_nmls_license',
    # Federal Sources - USPTO
    'USPTOScraper',
    'Trademark',
    'Patent',
    'TrademarkSearch',
    'PatentSearch',
    'TrademarkStatus',
    'PatentType',
    'PatentStatus',
    # Federal Sources - SEC
    'SECEdgarScraper',
    'SECFiling',
    'SECCompany',
    'SECSearch',
    'SECFilingType',
    # Federal Sources - FDIC
    'FDICScraper',
    'Bank',
    'BankBranch',
    'BankSearch',
    'BankStatus',
    # Federal Sources - Census
    'CensusScraper',
    'CensusData',
    'CensusSearch',
    # Federal Sources - FHFA
    'FHFAScraper',
    'HousePriceIndex',
    # Federal Sources - BLS
    'BLSScraper',
    'LaborStatistic',
    'UnemploymentData',
    # Federal Sources - Functions
    'search_trademarks',
    'search_sec_filings',
    'search_banks',
    # News API
    'NewsAPIScraper',
    'NewsArticle',
    'NewsSource',
    'NewsSearch',
    'NewsCategory',
    'NewsSentiment',
    'NewsSourceType',
    'GoogleNewsScraper',
    'LocalNewsAggregator',
    'PressReleaseAggregator',
    'PressRelease',
    'EntityNewsFinder',
    'EntityNewsSearch',
    'search_news',
    'search_entity_news',
    'get_local_headlines',
    # FEC API
    'FECApiClient',
    'FECCandidate',
    'FECCommittee',
    'FECContribution',
    'CandidateOffice',
    'CandidateStatus',
    'PartyAffiliation',
    'CommitteeType',
    'search_fec_candidates',
    'search_fec_contributions',
    # FDA API
    'FDAApiClient',
    'FDAEndpoint',
    'DrugAdverseEvent',
    'DrugRecall',
    'DeviceRecall',
    'FoodRecall',
    'DrugLabel',
    'RecallClassification',
    'RecallStatus',
    'search_drug_adverse_events_sync',
    'search_drug_recalls_sync',
    'search_food_recalls_sync',
    # EPA API
    'EPAApiClient',
    'EPADatabase',
    'EPAFacility',
    'EPAViolation',
    'EPAEnforcement',
    'TRIRelease',
    'SuperfundSite',
    'AirQualityData',
    'WaterSystem',
    'ViolationType',
    'ComplianceStatus',
    'search_facilities_sync',
    'search_violations_sync',
    'search_superfund_sites_sync',
    # FMCSA API
    'FMCSAApiClient',
    'Carrier',
    'CarrierBasics',
    'Inspection',
    'Crash',
    'OperatingAuthority',
    'CarrierOperationType',
    'SafetyRating',
    'OperatingStatus',
    'get_carrier_sync',
    'search_carriers_sync',
    'get_carrier_inspections_sync',
    # Vital Records
    'VitalRecordsScraper',
    'DeathRecord',
    'MarriageRecord',
    'DivorceRecord',
    'BurialRecord',
    'RecordType',
    'RecordSource',
    'get_vital_records_office',
    'search_death_records_sync',
    # Criminal Records
    'CriminalRecordsScraper',
    'SexOffender',
    'Inmate',
    'Warrant',
    'MostWanted',
    'CriminalCase',
    'OffenderType',
    'InmateStatus',
    'WarrantType',
    'CrimeCategory',
    'search_sex_offenders_sync',
    'search_inmates_sync',
    # Voter Records
    'VoterRecordsScraper',
    'VoterRegistration',
    'CampaignContribution',
    'ElectionResult',
    'StateVoterAccess',
    'VoterStatus',
    'VoterFileAccess',
    'PartyRegistration',
    'ElectionType',
    'get_voter_lookup_url',
    'get_state_election_resources',
    'check_registration_sync',
    # Regulatory Records
    'RegulatoryRecordsScraper',
    'OSHAInspection',
    'OSHAViolation',
    'MSHAInspection',
    'RegulatorySECFiling',
    'SECEnforcement',
    'ProductRecall',
    'RegulatoryViolationType',
    'InspectionType',
    'RegulatorySECFilingType',
    'STATE_REGULATORY_URLS',
    'search_osha_inspections_sync',
    'search_sec_filings_sync',
    'search_product_recalls_sync',
    # Financial Records
    'FinancialRecordsScraper',
    'BankruptcyCase',
    'TaxLien',
    'Judgment',
    'NonprofitOrg',
    'UnclaimedProperty',
    'BankruptcyChapter',
    'BankruptcyStatus',
    'LienType',
    'NonprofitType',
    'get_unclaimed_property_url',
    'search_nonprofits_sync',
    'get_nonprofit_990s_sync',
    # Asset Records
    'AssetRecordsScraper',
    'Aircraft',
    'Pilot',
    'Vessel',
    'StateBoatRegistration',
    'AircraftCategory',
    'AircraftType',
    'RegistrationStatus',
    'VesselType',
    'VesselService',
    'get_faa_resources',
    'get_state_boat_url',
    'search_aircraft_sync',
    # Education Records
    'EducationRecordsScraper',
    'School',
    'SchoolDistrict',
    'TeacherLicense',
    'College',
    'SchoolLevel',
    'SchoolType',
    'EducationLicenseStatus',
    'STATE_TEACHER_LICENSE_URLS',
    'search_colleges_sync',
    'search_schools_sync',
    'search_districts_sync',
    # Employment Records
    'EmploymentRecordsScraper',
    'FederalAward',
    'GovernmentSalary',
    'PensionRecord',
    'FederalAgency',
    'AwardType',
    'EmployeeType',
    'STATE_SALARY_DATABASES',
    'STATE_PENSION_DATABASES',
    'search_federal_awards_sync',
    'search_federal_agencies_sync',
    # Health Safety Records
    'HealthSafetyRecordsScraper',
    'HealthcareProvider',
    'NursingHome',
    'Hospital',
    'ExcludedProvider',
    'HomeHealthAgency',
    'ProviderType',
    'HealthLicenseStatus',
    'StarRating',
    'STATE_HEALTH_LICENSE_URLS',
    'search_providers_sync',
    'search_nursing_homes_sync',
    'search_hospitals_sync',
    # Transportation Records
    'TransportationRecordsScraper',
    'VehicleRecall',
    'VehicleComplaint',
    'VehicleSafetyRating',
    'VINDecodeResult',
    'CDLHolder',
    'VehicleType',
    'VehicleRecallStatus',
    'CDLClass',
    'CDLEndorsement',
    'STATE_DMV_URLS',
    'CDL_VERIFICATION_RESOURCES',
    'decode_vin_sync',
    'search_recalls_sync',
    'search_complaints_sync',
    'get_safety_ratings_sync',
    # Lottery Winners
    'LotteryWinner',
    'LotteryGame',
    'PrizeType',
    'PaymentOption',
    'ClaimStatus',
    'LotterySearchCriteria',
    'LotterySearchResult',
    'BaseLotteryAPI',
    'get_lottery_api',
    'search_lottery_winners',
    'get_recent_lottery_winners',
    'get_jackpot_winners',
    'search_all_states_lottery_winners',
    # Registered Agents
    'RegisteredAgentRecord',
    'RepresentedEntity',
    'AgentStatus',
    'AgentType',
    'RegisteredAgentEntityType',
    'RegisteredAgentSearchCriteria',
    'RegisteredAgentSearchResult',
    'BaseRegisteredAgentAPI',
    'get_registered_agent_api',
    'search_registered_agents',
    'search_agents_by_entity',
    'search_all_states_agents',
    # Childcare Licenses
    'ChildcareFacility',
    'ChildcareInspection',
    'ChildcareViolation',
    'Capacity',
    'ChildcareFacilityType',
    'ChildcareLicenseStatus',
    'ChildcareLicenseType',
    'ChildcareInspectionType',
    'ChildcareViolationType',
    'ChildcareSearchCriteria',
    'ChildcareSearchResult',
    'BaseChildcareAPI',
    'get_childcare_api',
    'search_childcare_facilities',
    'search_childcare_by_zip',
    'search_all_states_childcare',
    # Veterinary Licenses
    'VeterinaryLicense',
    'VetDisciplinaryRecord',
    'VetLicenseType',
    'VetLicenseStatus',
    'VetSpecialty',
    'VetDisciplinaryAction',
    'VetSearchCriteria',
    'VetSearchResult',
    'BaseVeterinaryBoardAPI',
    'get_vet_board_api',
    'search_veterinary_licenses',
    'verify_veterinary_license',
    'search_all_states_vet_licenses',
    # Immigration Court
    'ImmigrationCourt',
    'ImmigrationJudge',
    'JudgeStatistics',
    'CourtStatistics',
    'PrecedentDecision',
    'NationalStatistics',
    'ImmigrationCaseType',
    'CaseOutcome',
    'ReliefType',
    'CourtStatus',
    'IMMIGRATION_COURTS',
    'BaseImmigrationCourtAPI',
    'get_all_immigration_courts',
    'get_immigration_courts_by_state',
    'get_detention_courts',
    'get_national_statistics',
    'get_court_statistics',
    'search_precedent_decisions',
    'get_judge_statistics',
    'get_backlog_by_court',
    'get_asylum_grant_rates',
    # Foster Care
    'ChildWelfareAgency',
    'FosterCareStatistics',
    'FosterCareRequirements',
    'FosterCareAgencyType',
    'FosterCareLicenseStatus',
    'ServiceArea',
    'STATE_CHILD_WELFARE_AGENCIES',
    'BaseFosterCareAPI',
    'get_foster_care_api',
    'get_state_child_welfare_contact',
    'get_all_state_contacts',
    'search_foster_care_agencies',
    'get_foster_care_statistics',
    'get_foster_care_requirements',
    'search_all_states_foster_stats',
    # Pest Control Licenses
    'PestControlLicense',
    'PestControlDisciplinaryAction',
    'PestControlCompany',
    'PestControlLicenseType',
    'PestControlLicenseStatus',
    'PestControlCategory',
    'STATE_PEST_CONTROL_AGENCIES',
    'BasePestControlAPI',
    'STATE_PEST_CONTROL_APIS',
    'get_state_pest_control_agency',
    'search_pest_control_licenses',
    'verify_pest_control_license',
    'search_pest_control_companies',
    'search_all_states_pest_control',
    # Campaign Donors (State)
    'StateCampaignContribution',
    'StateCandidate',
    'StateCommittee',
    'DonorSummary',
    'ContributionType',
    'DonorType',
    'OfficeLevel',
    'ElectionCycle',
    'STATE_CAMPAIGN_FINANCE',
    'BaseStateCampaignFinanceAPI',
    'STATE_CAMPAIGN_APIS',
    'get_state_campaign_database',
    'search_state_contributions',
    'search_state_candidates',
    'get_donor_history',
    'search_all_states_contributions',
    # Building Permits
    'BuildingPermitType',
    'BuildingPermitStatus',
    'PropertyUse',
    'Contractor',
    'BuildingInspection',
    'BuildingPermit',
    'BuildingPermitsAPI',
    'search_permits_by_address',
    'search_permits_by_owner',
    'search_permits_by_contractor',
    'get_permit',
    'get_recent_permits',
    'get_high_value_permits',
    'get_building_permit_jurisdictions',
    # Census API
    'CensusDataset',
    'GeographyLevel',
    'CensusRecord',
    'BusinessPatternRecord',
    'PopulationEstimate',
    'CensusApiScraper',
    'get_census_scraper',
    'get_county_demographics',
    'get_county_population',
    'get_available_datasets',
    'get_common_variables',
    'get_state_fips',
    'get_all_state_fips',
    # Code Violations
    'CodeViolationType',
    'ViolationStatus',
    'PriorityLevel',
    'ComplaintSource',
    'ViolationProperty',
    'ViolationPropertyOwner',
    'ViolationInspection',
    'ViolationFine',
    'ViolationHearing',
    'CodeViolationRecord',
    'CodeViolationsAPI',
    'search_violations_by_address',
    'search_violations_by_owner',
    'get_violation_by_case',
    'get_open_violations',
    'get_recent_code_violations',
    'get_city_code_enforcement_info',
    'get_code_violations_cities',
    'get_code_violations_coverage_stats',
    # DBA Filings
    'DBAFilingType',
    'DBAStatus',
    'BusinessStructure',
    'DBARegistrant',
    'DBAFiling',
    'DBAFilingsAPI',
    'search_dba_by_business_name',
    'search_dba_by_registrant',
    'get_dba_by_filing_number',
    'get_dba_filing_requirements',
    'get_dba_county_office_info',
    'get_state_dba_info',
    'get_all_dba_state_info',
    'get_dba_coverage_stats',
    # Environmental Records
    'EnvironmentalRecordType',
    'EnvironmentalComplianceStatus',
    'EnvironmentalRecord',
    'EnvironmentalRecordsScraper',
    'get_environmental_scraper',
    'search_environmental_facilities',
    'get_environmental_sources',
    # Evictions
    'EvictionType',
    'EvictionCaseStatus',
    'EvictionPartyRole',
    'EvictionParty',
    'EvictionEvent',
    'EvictionJudgment',
    'EvictionRecord',
    'EvictionsAPI',
    'search_evictions_by_defendant',
    'search_evictions_by_plaintiff',
    'search_evictions_by_address',
    'get_eviction_case',
    'get_recent_evictions',
    'get_state_eviction_info',
    'get_eviction_counties',
    # Foreclosures
    'ForeclosureStage',
    'ForeclosureType',
    'ForeclosurePropertyType',
    'MortgageInfo',
    'AuctionInfo',
    'ForeclosureRecord',
    'ForeclosuresAPI',
    'search_foreclosures_by_address',
    'search_foreclosures_by_county',
    'search_foreclosure_auctions',
    'search_reo_properties',
    'get_state_foreclosure_info',
    'get_foreclosure_states',
    # Government Contracts
    'ContractType',
    'AwardStatus',
    'CompetitionType',
    'ContractRecord',
    'GovernmentContractsScraper',
    'get_contracts_scraper',
    'search_contracts',
    'get_contracts_sources',
    # Hunting Fishing
    'HuntingFishingLicenseType',
    'HuntingFishingLicenseStatus',
    'ResidencyStatus',
    'HarveyReportStatus',
    'LicenseHolder',
    'HarvestRecord',
    'HuntingFishingLicenseRecord',
    'HuntingFishingAPI',
    'search_hunting_fishing_licenses',
    'get_hunting_fishing_license',
    'get_harvest_data',
    'get_license_types',
    'get_license_requirements',
    'verify_hunting_fishing_license',
    'get_state_dnr_info',
    'get_all_state_dnr_agencies',
    'get_federal_duck_stamp',
    'get_hunting_fishing_coverage_stats',
    # Inmate Records
    'CustodyStatus',
    'InmateFacilityType',
    'SecurityLevel',
    'InmateRecord',
    'FacilityInfo',
    'InmateRecordsScraper',
    'get_inmate_scraper',
    'search_inmate_records',
    'search_federal_inmates',
    'search_inmate_sex_offenders',
    'get_inmate_sources',
    # Mechanic Liens
    'MechanicLienType',
    'MechanicLienStatus',
    'ClaimantType',
    'MechanicLienPropertyType',
    'LienClaimant',
    'LienPropertyOwner',
    'LienProperty',
    'WorkDescription',
    'MechanicLienRecord',
    'MechanicLiensAPI',
    'search_liens_by_property',
    'search_liens_by_lien_owner',
    'search_liens_by_claimant',
    'get_lien_by_document',
    'get_recent_liens',
    'get_lien_law_info',
    'get_lien_filing_deadline',
    'get_lien_county_recorder_info',
    'get_all_state_lien_laws',
    'get_mechanic_liens_coverage_stats',
    # Permits Inspections
    'PermitsPermitType',
    'PermitsInspectionType',
    'PermitsPermitStatus',
    'PermitsInspectionResult',
    'PermitRecord',
    'InspectionRecord',
    'PermitsInspectionsScraper',
    'get_permits_scraper',
    'search_building_permits',
    'get_permits_sources',
    # Probate Records
    'ProbateCaseType',
    'ProbateCaseStatus',
    'ProbatePartyRole',
    'ProbateDocumentType',
    'ProbateParty',
    'ProbateDocument',
    'ProbateAsset',
    'ProbateEvent',
    'ProbateRecord',
    'ProbateRecordsAPI',
    'search_probate_by_decedent',
    'get_probate_case',
    'search_probate_by_heir',
    'get_recent_probate_filings',
    'get_state_probate_info',
    'get_county_probate_info',
    'get_small_estate_limit',
    'get_all_state_probate_info',
    'get_probate_coverage_stats',
    # Property Records
    'PropertyRecordType',
    'PropertyRecord',
    'PropertyRecordsScraper',
    'get_property_scraper',
    'search_property',
    'get_property_sources',
    # Restaurant Inspections
    'RestaurantInspectionType',
    'RestaurantInspectionResult',
    'RestaurantFacilityType',
    'ViolationSeverity',
    'ViolationCategory',
    'RestaurantViolation',
    'FoodEstablishment',
    'RestaurantInspectionRecord',
    'RestaurantInspectionsAPI',
    'search_restaurant_inspections',
    'search_restaurant_by_address',
    'get_recent_restaurant_inspections',
    'get_failed_inspections',
    'get_critical_violations',
    'get_establishment_history',
    'get_restaurant_jurisdictions',
    'get_state_health_info',
    'get_restaurant_coverage_stats',
    # SEC API
    'SECApiFilingType',
    'SECApiFilingStatus',
    'SECApiFilingRecord',
    'InsiderTransaction',
    'SECApiScraper',
    'get_sec_api_scraper',
    'search_sec_api_filings',
    'get_sec_endpoints',
    # Tax Records
    'TaxRecordType',
    'TaxStatus',
    'TaxRecord',
    'TaxRecordsScraper',
    'get_tax_scraper',
    'search_property_taxes',
    'get_tax_sources',
    # UCC Filings
    'UCCFilingType',
    'UCCStatus',
    'DebtorType',
    'CollateralType',
    'UCCParty',
    'UCCAmendment',
    'UCCFilingRecord',
    'UCCFilingsAPI',
    'search_ucc_by_debtor',
    'search_ucc_by_secured_party',
    'search_ucc_by_state',
    'get_ucc_filing',
    'get_ucc_available_states',
    # USPTO API
    'USPTOPatentType',
    'USPTOPatentStatus',
    'USPTOTrademarkStatus',
    'PatentRecord',
    'USPTOTrademarkRecord',
    'USPTOApiScraper',
    'get_uspto_scraper',
    'search_patents',
    'search_uspto_trademarks',
    'get_uspto_endpoints',
]
