#!/usr/bin/env bash
# =============================================================================
# DataGod Secrets Management
#
# Generates and manages production secrets securely.
# Secrets are stored as Docker secrets (Swarm mode) or written to .env.production.
#
# Usage:
#   ./scripts/manage-secrets.sh generate    # Generate all secrets
#   ./scripts/manage-secrets.sh rotate      # Rotate JWT + API keys
#   ./scripts/manage-secrets.sh verify      # Verify secrets are set
#   ./scripts/manage-secrets.sh export      # Export to .env.production
# =============================================================================

set -euo pipefail

ENV_FILE=".env.production"
SECRETS_DIR=".secrets"

# --- Helper: Generate a cryptographically secure random string ---
generate_secret() {
    local length="${1:-64}"
    python3 -c "import secrets; print(secrets.token_urlsafe(${length}))" 2>/dev/null \
        || openssl rand -base64 "${length}" | tr -d '\n/+=' | head -c "${length}"
}

# --- Required secrets and their descriptions ---
declare -A SECRET_DESCRIPTIONS=(
    ["SECRET_KEY"]="Django/FastAPI application secret key"
    ["JWT_SECRET"]="JSON Web Token signing secret"
    ["DB_PASSWORD"]="PostgreSQL database password"
    ["REDIS_PASSWORD"]="Redis cache password"
    ["STRIPE_SECRET_KEY"]="Stripe API secret key (from dashboard)"
    ["STRIPE_WEBHOOK_SECRET"]="Stripe webhook signing secret"
    ["ENCRYPTION_KEY"]="Data encryption key for PII fields"
)

# --- Action: generate ---
cmd_generate() {
    echo "╔══════════════════════════════════════════════════╗"
    echo "║  DataGod Secrets Generator                       ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""

    mkdir -p "${SECRETS_DIR}"

    # Auto-generated secrets
    local secrets_generated=0

    for key in SECRET_KEY JWT_SECRET DB_PASSWORD REDIS_PASSWORD ENCRYPTION_KEY; do
        local file="${SECRETS_DIR}/${key,,}"
        if [ ! -f "${file}" ]; then
            generate_secret 48 > "${file}"
            chmod 600 "${file}"
            echo "  ✓ Generated: ${key} → ${file}"
            ((secrets_generated++))
        else
            echo "  · Exists:    ${key} (skipped)"
        fi
    done

    # Stripe keys need manual entry
    for key in STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET; do
        local file="${SECRETS_DIR}/${key,,}"
        if [ ! -f "${file}" ]; then
            echo "  ⚠ Manual:    ${key} — set via: echo 'your-key' > ${file}"
        fi
    done

    echo ""
    echo "Generated ${secrets_generated} new secrets in ${SECRETS_DIR}/"
    echo "Run '$0 export' to write them to ${ENV_FILE}"
}

# --- Action: rotate ---
cmd_rotate() {
    echo "Rotating application secrets..."

    for key in SECRET_KEY JWT_SECRET ENCRYPTION_KEY; do
        local file="${SECRETS_DIR}/${key,,}"
        local backup="${file}.bak.$(date +%Y%m%d%H%M%S)"
        if [ -f "${file}" ]; then
            cp "${file}" "${backup}"
            echo "  · Backed up: ${key} → ${backup}"
        fi
        generate_secret 48 > "${file}"
        chmod 600 "${file}"
        echo "  ✓ Rotated:   ${key}"
    done

    echo ""
    echo "⚠  IMPORTANT: After rotating secrets, you must:"
    echo "   1. Run '$0 export' to update ${ENV_FILE}"
    echo "   2. Restart all containers: docker-compose restart"
    echo "   3. Note: existing JWT tokens will be invalidated"
}

# --- Action: verify ---
cmd_verify() {
    echo "Verifying secrets..."
    echo ""

    local all_ok=true

    for key in "${!SECRET_DESCRIPTIONS[@]}"; do
        local file="${SECRETS_DIR}/${key,,}"
        local desc="${SECRET_DESCRIPTIONS[$key]}"
        if [ -f "${file}" ] && [ -s "${file}" ]; then
            local len
            len=$(wc -c < "${file}" | tr -d ' ')
            echo "  ✓ ${key} (${len} bytes) — ${desc}"
        else
            echo "  ✗ ${key} — MISSING — ${desc}"
            all_ok=false
        fi
    done

    echo ""
    if [ "${all_ok}" = true ]; then
        echo "All secrets are configured. ✓"
    else
        echo "Some secrets are missing. Run '$0 generate' first."
        return 1
    fi
}

# --- Action: export ---
cmd_export() {
    echo "Exporting secrets to ${ENV_FILE}..."

    cat > "${ENV_FILE}" << 'HEADER'
# =============================================================================
# DataGod Production Environment Configuration
# Generated by manage-secrets.sh — DO NOT COMMIT TO VERSION CONTROL
# =============================================================================

ENVIRONMENT=production
LOG_LEVEL=INFO

HEADER

    for key in SECRET_KEY JWT_SECRET DB_PASSWORD REDIS_PASSWORD ENCRYPTION_KEY STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET; do
        local file="${SECRETS_DIR}/${key,,}"
        if [ -f "${file}" ]; then
            echo "${key}=$(cat "${file}")" >> "${ENV_FILE}"
        else
            echo "# ${key}=  # Not yet configured" >> "${ENV_FILE}"
        fi
    done

    # Add non-secret config
    cat >> "${ENV_FILE}" << 'CONFIG'

# Database
POSTGRES_USER=datagod
POSTGRES_DB=datagod

# Domain (update for your deployment)
DOMAIN=yourdomain.com
CORS_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
NEXT_PUBLIC_API_URL=https://api.yourdomain.com

# Ports
API_PORT=8000
FRONTEND_PORT=3000
DB_PORT=5432
REDIS_PORT=6379
CONFIG

    chmod 600 "${ENV_FILE}"
    echo "  ✓ Written to ${ENV_FILE} (permissions: 600)"
    echo ""
    echo "Usage: docker-compose --env-file ${ENV_FILE} -f docker-compose.prod.yml up -d"
}

# --- Main ---
case "${1:-help}" in
    generate) cmd_generate ;;
    rotate)   cmd_rotate ;;
    verify)   cmd_verify ;;
    export)   cmd_export ;;
    *)
        echo "DataGod Secrets Manager"
        echo ""
        echo "Usage: $0 {generate|rotate|verify|export}"
        echo ""
        echo "  generate  Create all required secrets"
        echo "  rotate    Rotate JWT + encryption keys"
        echo "  verify    Check all secrets are configured"
        echo "  export    Write secrets to .env.production"
        ;;
esac
